name: Captura de Telas Diaria

on:
  workflow_dispatch: # Permite que você clique em um botão no GitHub para rodar quando quiser
  schedule:
    - cron: '0 12 * * *' # Executa automaticamente todo dia às 12:00 UTC (09:00 Horário de Brasília)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Playwright e Dependencias do Sistema
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Rodar Automacao
        run: python main.py

      - name: Salvar os Prints Gerados (Artifacts)
        if: always() # Garante que vai salvar os prints mesmo se o script der erro em algum termo
        uses: actions/upload-artifact@v4
        with:
          name: prints-amazon-e-mercadolivre-${{ github.run_id }}
          path: prints/ # Salva a pasta inteira contendo as subpastas 'amazon' e 'mercadolivre'
          retention-days: 7 # Os prints ficam guardados no GitHub por 7 dias para você baixar
